{% set name = "COMPSs" %}
{% set version = "3.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://compss.bsc.es/repo/sc/stable/COMPSs_{{ version }}.tar.gz
  sha256: 7b0e52e275b3890aa59f5b5ae40e13b49701269c8d1b2ff76c0aed27d30d6239

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - make
    - openjdk =11
    - automake
    - autoconf
    - libtool
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - libboost-python-devel
    - libboost-devel
    - python 3.10.*
    - pip
    - setuptools
    - zlib
  host:
    - pip
    - python 3.10.*
    - setuptools
    - openjdk =11
  run:
    - python 3.10.*
    - setuptools
    - openjdk =11
    - nb_conda_kernels
    - dill
    - mpi4py
    - guppy3

test:
  imports:
    - pycompss
  commands:
    - echo $COMPSS_HOME
    - runcompss -v

about:
  home: http://compss.bsc.es
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'
  license: Apache-2.0
  license_file: LICENSE.txt
  doc_url: https://compss-doc.readthedocs.io
  dev_url: https://github.com/bsc-wdc/compss

extra:
  recipe-maintainers:
    - RubenChM
